version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
